In [11]:
import pandas as pd

In [12]:
df=pd.read_csv('company_data.csv')
print(df.shape)

(165, 7)

In [14]:
import pandas as pd

# Function to split and handle missing values
def split_person_quoted(row):
    """
    Splits the 'person_quoted' field into three parts:
    - Person name: The part before the first comma.
    - Role in the company: The part between the first and second commas.
    - Company name: The part after the second comma.

    The function then removes the company name and returns only the person name and role as two separate columns.
    It also handles missing values (NaN), returning None for both columns when the value is missing.

    Parameters:
    ----------
    row : str or NaN
        The string containing the name, role, and company in the format 'Name, Role, Company'.
        If the value is missing (NaN), None is returned for both columns.

    Returns:
    -------
    pd.Series
        A pandas Series containing two values:
        - Person name: The part before the first comma.
        - Role in the company: The part between the first and second commas.

    If the input is missing (NaN), the function will return None for both columns.
    """
    # Check if the value is missing (NaN)
    if pd.isna(row):
        return pd.Series([None, None])  # Return None for both columns if missing

    # Split the input string into three parts: person name, role, and company
    parts = row.split(',', 2)

    # Ensure there are exactly three parts (person, role, company)
    if len(parts) == 3:
        person_name, role_in_company, company_name = parts
        return pd.Series([person_name, role_in_company])  # Return the first two parts only
    else:
        return pd.Series([None, None])  # Return None if the format is incorrect


# Apply the function and create the new columns
df[['Person Name', 'Role in Company']] = df['person_quoted'].apply(split_person_quoted)

In [15]:
df.head()

,company_name,industry,location,partners,person_quoted,product_url,region,Person Name,Role in Company
0,TSB Bank Limited,Financial services,New Zealand,NaN,"Lisa Macnee, Head of Digital and Customer Enga...",https://www.genesys.com/customer-stories/tsb-b...,APAC,Lisa Macnee,Head of Digital and Customer Engagement Center
1,ConTe.it,Insurance,Italy,NaN,"Francesco Del Gallo, Product Manager, ConTe.it",https://www.genesys.com/customer-stories/conte...,EMEA,Francesco Del Gallo,Product Manager
2,DKV Euro Service GmbH & Co. KG,Transportation,Germany,['VR Voice GmbH'],"Robert Trojan, Team Manager Workplace and Netw...",https://www.genesys.com/customer-stories/dkv/,EMEA,Robert Trojan,Team Manager Workplace and Network Services
3,Probe Group,Business process outsourcing,"Australia, New Zealand and the Philippines",NaN,"Rohan Khanna, CTO, Probe Group",https://www.genesys.com/customer-stories/probe...,APAC,Rohan Khanna,CTO
4,eFinancial,Insurance,U.S.,NaN,"Paul Bourdeaux, Chief Information Officer, Ver...",https://www.genesys.com/customer-stories/efina...,NaN,Paul Bourdeaux,Chief Information Officer

In [16]:
df.to_csv('company_data.csv')